// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Todo {
    "ID": number;
    "Task": string;
    "Finished": boolean;
    "TodoGroupID": number;
}

export interface TodoGroup {
    "ID": number;
    "Title": string;
    "Todos": Todo[] | null;
}
