// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function AddTodo(groupId: number, task: string): $CancellablePromise<model$0.Todo> {
    return $Call.ByID(2651540288, groupId, task);
}

export function CreateTodoGroup(title: string): $CancellablePromise<model$0.TodoGroup> {
    return $Call.ByID(2437579968, title);
}

export function DeleteTodoGroup(groupId: number): $CancellablePromise<void> {
    return $Call.ByID(2086202441, groupId);
}

export function GetAllTodoGroup(): $CancellablePromise<model$0.TodoGroup[] | null> {
    return $Call.ByID(1878489209);
}

export function RemoveTodo(todoId: number): $CancellablePromise<void> {
    return $Call.ByID(2494639593, todoId);
}

export function UpdateTodo(todoId: number, task: string, finished: boolean): $CancellablePromise<void> {
    return $Call.ByID(3709803560, todoId, task, finished);
}

export function UpdateTodoGroup(groupId: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(2256161323, groupId, title);
}
